### ISSUE TITLE
Cannot find color scheme

### ISSUE THREAD

**Issue by iluuu1994** [TyOverby/nvim#1]
I've not touched neovim since installing it via homebrew and since you're setup looked pretty good I thought I'd try it :)

Unfortunately I got the following error:

```
Error detected while processing /Users/ilijatovilo/.config/nvim/init.vim:
line   50:
E185: Cannot find color scheme 'gruvbox'
Press ENTER or type command to continue
```

It looks like neovim is not downloading the packages from the `init.vim` file.
It's starting instantly, it does not look like it's doing much.

Any clue on how to fix this?

**Comment by TyOverby** [comment]
Ah yeah, I should add this to the instructions.  You need to run `PlugInstall` on the first run of neovim.

**Comment by iluuu1994** [comment]
That did the trick, thanks! Sorry, as mentioned I've not used NeoVim or it's package system before. Thanks!

**Comment by TyOverby** [comment]
Great!  Thanks for the bug report, I just updated the readme to have the updated instructions.

**Comment by TyOverby** [comment]
@iluuu1994 I also added a section on my custom keybindings. 

I just picked up neovim yesterday, so let me know if you find anything else cool!

**Comment by iluuu1994** [comment]
@TyOverby Sure thing!
